#!/bin/bash

## variables
##
## @HOST_FQDN, value corresponds to the assignment set in 'install_foreman',
##     when defining /etc/hosts, and /etc/hostname.
##
HOST_IP='192.168.0.10'
HOST_FQDN='foreman.sandbox.local'
OS_VERSION=$(rpm -qa \*-release | grep -Ei "oracle|redhat|centos" | cut -d"-" -f3)
PUPPET_6_RPM='puppetlabs-release-el-6.noarch'
PUPPET_7_RPM='puppetlabs-release-pc1-el-7.noarch'
PATH_PUPPET='/opt/puppetlabs/bin'

## set proxy, conditionally set additional variables
##
## Note: only a vagrant implementation should have a private ssh key named
##       'puppetagent_vagrant.private'.
##
if [ -f /vagrant/.ssh/puppetagent_vagrant.private ]; then

    PATH_BASH="PATH=\$PATH\:\$HOME/.local/bin"
    USER='provisioner'
    BASH_PROFILE="/home/$USER/.bash_profile"

else

    ## local variables
    CORRECT_PROXY='n'

    ## prompt proxy configurations
    while [ "${CORRECT_PROXY,,}" != 'y' ] || \
        [ "${CORRECT_PROXY,,}" != 'yes' ] || \
        [ "${CORRECT_PROXY,,}" != 'true' ] || \
        [ "${CORRECT_PROXY,,}" != 'ok' ]; do

        ## acquire proxy ip
        read -p 'Enter your proxy ip > ' PROXY_IP

        ## acquire proxy port
        read -p 'Enter your proxy port > ' PROXY_PORT

        ## verify submission
        echo "Your proxy: $PROXY_IP:$PROXY_PORT"
        read -p 'Is this correct (y) > ' CORRECT_PROXY
    done

    BASH_PROFILE='/root/.bash_profile'
    PATH_BASH="PATH=\$PATH\:\$HOME/bin"

    export http_proxy=http://"$PROXY_IP":"$PROXY_PORT"
    export https_proxy=https://"$PROXY_IP":"$PROXY_PORT"

fi

## install puppetagent
if [ "$OS_VERSION" -lt 7 ]; then
    rpm -e "$PUPPET_6_RPM"
    rpm -ivh http://yum.puppetlabs.com/"$PUPPET_6_RPM".rpm
else
    rpm -e "$PUPPET_7_RPM"
    rpm -Uvh https://yum.puppetlabs.com/"$PUPPET_7_RPM".rpm
fi
sudo yum install -y puppet
echo 'Puppet agent installed.'

## ensure system path has puppet reference
##
##  Note: an arbitrary choice was made to use ',' as the delimiting character.
##        Any instances of ',' between the defined delimiters will need to be
##        escaped.
##
[[ $PATH_PUPPET !~ $PATH ]] && sed -i "s,$PATH_BASH,$PATH_BASH:$PATH_PUPPET,g $BASH_PROFILE"
echo 'System path configured for puppet.'

# add reference to puppetserver
echo "$HOST_IP	$HOST_FQDN" >> /etc/hosts
sudo /etc/init.d/network restart

## get hostname
HOSTNAME=$(hostnamectl --static)

## assign puppet agent configuration
sudo /opt/puppetlabs/bin/puppet config set server "$HOST_FQDN"
sudo /opt/puppetlabs/bin/puppet config set certname "$HOSTNAME"

## reboot to apply above changes
##
## Note: only a vagrant implementation should have a private ssh key named
##       'puppetagent_vagrant.private'.
##
if ! [ -f /vagrant/.ssh/puppetagent_vagrant.private ]; then
    sudo reboot
fi